/**
 * Client-side LLM service — Sumopod (OpenAI compatible chat completions)
 *
 * Browser TIDAK memanggil provider LLM langsung (CORS + API key tidak boleh
 * ter-expose ke client bundle). Semua request diproxy via Vercel serverless:
 *   - klasifikasi berita → POST /api/classify
 *   - prompt bebas       → POST /api/llm
 */

import { classifyContent as classifyViaApi, llmGenerate } from './api';
import type { ClassificationResult } from './api';

export type { ClassificationResult } from './api';

/** Kirim prompt bebas ke LLM, kembalikan plain text */
export async function generateContent(prompt: string): Promise<string> {
  const result = await llmGenerate(prompt);
  if (!result.text) {
    throw new Error('No response from LLM');
  }
  return result.text;
}

export async function classifyContent(title: string, content: string): Promise<ClassificationResult> {
  // Selalu lewat /api/classify supaya API key LLM tetap di server
  return classifyViaApi(title, content);
}

// ================= AUTO CAPTION GENERATOR =================
// Generate caption Instagram dari data carousel via LLM (Sumopod)

export interface CaptionContext {
  handle?: string;
  badgeText?: string;
  title: string;
  description?: string;
  source?: string;
  tldrCards?: string[];
  metrics?: { label: string; value: string }[];
  bullets?: string[];
  category?: string;
}

export async function generateInstagramCaption(context: CaptionContext): Promise<string> {
  const tldrText = (context.tldrCards || []).map(t => `• ${t}`).join('\n');
  const metricText = (context.metrics || []).map(m => `• ${m.label}: ${m.value}`).join('\n');
  const bulletText = (context.bullets || []).map(b => `• ${b}`).join('\n');

  const prompt = `
Kamu adalah Social Media Content Creator untuk akun Instagram finansial @sahamfyp. 
Tugasmu adalah membuat SATU caption Instagram menarik untuk post carousel tentang berita saham Indonesia.

STYLE GUIDELINES:
- Bahasa: Indonesia kasual (campur dengan slang muda seperti "kok bisa", "nggak", "dong", dll) — natural, bukan bahasa terlalu formal
- Atraktor: hook kuat di kalimat pertama (question, surprise, atau angka)
- Informasi: ringkasan dari data, pergerakan harga, keuntungan — informatif tapi kasual
- CTA: ajak audiens comment/share (contoh: "Lo pegang saham ini? Drop di komentar 👇")
- Disclaimer: selalu include "DYOR - Do Your Own Research" di end
- Format: maksimal 300 karakter (Instagram caption limit untuk carousel)
- Hashtags: 3-5 hashtag relevan (#saham #investasi #{ticker} #analisis #stock)

STRUCTURE:
1. Hook (1-2 kalimat)
2. Info utama (2-4 kalimat, dari data)
3. CTA (1 kalimat)
4. Hashtags + DYOR

OUTPUT: Text saja (plain text), NO quotes, NO markdown, NO json.

---
DATA CAROUSEL:
- Kategori: ${context.category || 'N/A'}
- Judul: ${context.title}
${context.description ? `- Deskripsi: ${context.description}` : ''}
${context.source ? `- Sumber: ${context.source}` : ''}
${context.badgeText ? `- Ticker: ${context.badgeText}` : ''}
${tldrText ? `\nTLDR POINTS:\n${tldrText}` : ''}
${metricText ? `\nMETRIC DATA:\n${metricText}` : ''}
${bulletText ? `\nBULLETS:\n${bulletText}` : ''}
`;

  const caption = await generateContent(prompt);
  if (!caption) {
    throw new Error('No caption generated by LLM');
  }
  return caption.trim();
}