// scripts/sync-env.mjs
// ============================================================
// Sync environment: maps non-prefixed (server) env vars to
// VITE_-prefixed (frontend) vars before `vite build`.
//
// Why: Frontend (Vite) ONLY exposes `import.meta.env.VITE_*`
// vars at build time, while serverless functions (api/**) read
// `process.env.KEY` (no prefix). So each secret needs TWO names
// in Vercel. This script makes the non-prefixed name the single
// source of truth and generates the VITE_ duplicates at build.
//
// Usage: node scripts/sync-env.mjs
//   - Vercel build: reads source values from `process.env`,
//     writes missing `VITE_*` keys into `.env.local` (gitignored)
//   - Local:        reads existing `.env.local` as fallback source,
//     appends only missing VITE_ keys (idempotent, safe to re-run)
// ============================================================

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

const ENV_PATH = resolve(process.cwd(), '.env.local');

// Mapping: non-prefixed (server / source of truth) -> VITE_ (frontend)
const MAP = [
  ['SUPABASE_URL', 'VITE_SUPABASE_URL'],
  ['SUPABASE_ANON_KEY', 'VITE_SUPABASE_ANON_KEY'],
  ['SUMOPOD_BASE_URL', 'VITE_LLM_BASE_URL'],
  ['SUMOPOD_MODEL', 'VITE_LLM_MODEL'],
  ['SECTORS_API_KEY', 'VITE_SECTORS_API_KEY'],
  ['REPLIZ_ACCESS_KEY', 'VITE_REPLIZ_ACCESS_KEY'],
  ['REPLIZ_SECRET_KEY', 'VITE_REPLIZ_SECRET_KEY'],
    ['REPLIZ_ACCOUNT_ID', 'VITE_REPLIZ_ACCOUNT_ID'],
  ['REPLIZ_TIKTOK_ACCOUNT_ID', 'VITE_REPLIZ_TIKTOK_ACCOUNT_ID'],
  ['CLOUDINARY_CLOUD_NAME', 'VITE_CLOUDINARY_CLOUD_NAME'],
  ['CLOUDINARY_UPLOAD_PRESET', 'VITE_CLOUDINARY_UPLOAD_PRESET'],
  ['N8N_API_KEY', 'VITE_N8N_API_KEY'],
];

// --- tiny dotenv parser (no external dependency needed) ---
function parseDotEnv(text) {
  const env = {};
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (key) env[key] = value;
  }
  return env;
}

function main() {
  const fileEnv = existsSync(ENV_PATH)
    ? parseDotEnv(readFileSync(ENV_PATH, 'utf8'))
    : {};

  const source = new Map();
  const missing = [];
  for (const [srcKey] of MAP) {
    const value = process.env[srcKey] ?? fileEnv[srcKey];
    source.set(srcKey, value ?? '');
    if (!value) missing.push(srcKey);
  }
  if (missing.length) {
    console.log(`[sync-env] warnings: missing source keys: ${missing.join(', ')}`);
  }

  const toWrite = [];
  for (const [srcKey, viteKey] of MAP) {
    const value = source.get(srcKey);
    if (!value) {
      console.log(`[sync-env] skip ${viteKey}: source "${srcKey}" not set`);
      continue;
    }
    if (fileEnv[viteKey]) {
      console.log(`[sync-env] ${viteKey} already present, left untouched`);
      continue;
    }
    toWrite.push(`${viteKey}=${value}`);
  }

  if (!toWrite.length) {
    console.log('[sync-env] nothing to write (all VITE_ keys already present)');
    return;
  }

  const existing = existsSync(ENV_PATH) ? readFileSync(ENV_PATH, 'utf8') : '';
  const block = [
    '',
    '# ==============================================',
    '# Generated by scripts/sync-env.mjs (build-time)',
    '# Source of truth: non-prefixed vars (process.env / .env.local)',
    '# ==============================================',
    ...toWrite,
  ].join('\n');

  const next =
    existing === '' || existing.endsWith('\n')
      ? existing + block
      : existing + '\n' + block;

  writeFileSync(ENV_PATH, next + '\n', 'utf8');
  console.log(`[sync-env] wrote ${toWrite.length} VITE_ key(s) -> ${ENV_PATH}`);
}

main();